// generated by Neptune Namespaces v4.x.x
// file: jest/index.js

(module.exports = require('./namespace'))

.addModules({
  StandardImport: require('./StandardImport')
});
require('./Config');
require('./Lib');
require('./Trackers');