// generated by Neptune Namespaces v4.x.x
// file: jest/index.js

(module.exports = require('./namespace'))

.addModules({
  CommitStateLibTest: require('./CommitStateLib.test')
});
require('./GitGenUi');