// generated by Neptune Namespaces v4.x.x
// file: jest/Config/index.js

(module.exports = require('./namespace'))

.addModules({
  UserConfig:     require('./UserConfig'),
  UserConfigTest: require('./UserConfig.test')
});