// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/PromptFor/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./PromptFor'))
.addModules({
  Autocomplete: require('./autocomplete')
});