// generated by Neptune Namespaces v4.x.x
// file: tests/GitGenUI/Lib/index.js

(module.exports = require('./namespace'))

.addModules({
  ApplyActions: require('./ApplyActions'),
  Git:          require('./Git'),
  SearchSort:   require('./SearchSort'),
  SourceRoot:   require('./SourceRoot')
});