// generated by Neptune Namespaces v4.x.x
// file: jest/Lib/index.js

(module.exports = require('./namespace'))

.addModules({
  ApplyActionsTest:   require('./ApplyActions.test'),
  CommitStateLibTest: require('./CommitStateLib.test'),
  SearchSortTest:     require('./SearchSort.test'),
  SourceRootTest:     require('./SourceRoot.test')
});