// generated by Neptune Namespaces v4.x.x
// file: GitGenUI/CommandsV2/index.js

(module.exports = require('./namespace'))

.addModules({
  Comment:     require('./Comment'),
  Commit:      require('./Commit'),
  Init:        require('./Init'),
  OpenTracker: require('./OpenTracker'),
  ShowCommit:  require('./ShowCommit'),
  Start:       require('./Start'),
  Status:      require('./Status'),
  WhoAmI:      require('./WhoAmI')
});