// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/CommandsV2/namespace.js

module.exports = require('../namespace').addNamespace(
  'CommandsV2',
  class CommandsV2 extends Neptune.PackageNamespace {}
);
