// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./GitGenUi'))
.addModules({
  Cli:               require('./Cli'),
  Config:            require('./Config'),
  ConfigShared:      require('./ConfigShared'),
  Git:               require('./Git'),
  GitGenUiPromptFor: require('./GitGenUiPromptFor'),
  InquirerPlus:      require('./InquirerPlus'),
  ProjectConfig:     require('./ProjectConfig'),
  StandardImport:    require('./StandardImport'),
  Tracker:           require('./Tracker'),
  UserConfig:        require('./UserConfig')
});
require('./Commands');
require('./Lib');
require('./PromptFor');
require('./Trackers');
require('./Widgets');