// generated by Neptune Namespaces v4.x.x
// file: GitGenUI/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./GitGenUI'))
.addModules({
  Cli:            require('./cli'),
  Config:         require('./Config'),
  Git:            require('./Git'),
  Interactive:    require('./interactive'),
  Pizza:          require('./pizza'),
  StandardImport: require('./StandardImport'),
  Tracker:        require('./Tracker')
});
require('./Lib');
require('./Trackers');