// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./GitGenUi'))
.addModules({
  Cli:                   require('./Cli'),
  Config:                require('./Config'),
  ConfigShared:          require('./ConfigShared'),
  GetInitialCommitState: require('./getInitialCommitState'),
  Git:                   require('./Git'),
  GitGenUiPromptFor:     require('./GitGenUiPromptFor'),
  ProjectConfig:         require('./ProjectConfig'),
  StandardImport:        require('./StandardImport'),
  Tracker:               require('./Tracker'),
  UserConfig:            require('./UserConfig')
});
require('./Commands');
require('./Lib');
require('./PostCommitActions');
require('./PromptFor');
require('./Trackers');
require('./Widgets');