// generated by Neptune Namespaces v4.x.x
// file: GitGenUI/index.js

(module.exports = require('./namespace'))

.addModules({
  Interactive: require('./interactive'),
  Main:        require('./main'),
  Pizza:       require('./pizza'),
  Tracker:     require('./Tracker')
});
require('./Trackers');