// generated by Neptune Namespaces v4.x.x
// file: GitGenUI/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./GitGenUI'))
.addModules({
  Cli:         require('./cli'),
  Interactive: require('./interactive'),
  Lib:         require('./Lib'),
  Pizza:       require('./pizza'),
  Tracker:     require('./Tracker')
});
require('./Trackers');