// generated by Neptune Namespaces v4.x.x
// file: GitGenUI/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'GitGenUi',
  (class GitGenUi extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./CommandsV2/namespace');
require('./Lib/namespace');
require('./Trackers/namespace');