// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Lib/_jest/index.js

(module.exports = require('./namespace'))

.addModules({
  CommitStateLibTestTest: require('./CommitStateLibTest.test')
});