// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Lib/_jest/namespace.js

module.exports = require('../namespace').addNamespace(
  'Jest',
  class Jest extends Neptune.PackageNamespace {}
);
