// generated by Neptune Namespaces v4.x.x
// file: tests/GitGenUI/index.js

(module.exports = require('./namespace'))

.addModules({
  InquirerPlus: require('./InquirerPlus')
});
require('./Lib');
require('./Trackers');