// generated by Neptune Namespaces v4.x.x
// file: tests/GitGenUI/index.js

(module.exports = require('./namespace'))

.addModules({
  UserConfig: require('./UserConfig')
});
require('./Lib');
require('./Trackers');