// generated by Neptune Namespaces v4.x.x
// file: tests/GitGenUI/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('GitGenUi');
require('./Trackers/namespace');