// generated by Neptune Namespaces v4.x.x
// file: tests/GitGenUI/namespace.js

module.exports = require('../namespace').addNamespace(
  'GitGenUi',
  class GitGenUi extends Neptune.PackageNamespace {}
);
require('./Lib/namespace');
require('./Trackers/namespace');