// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Trackers/namespace.js

module.exports = require('../namespace').addNamespace(
  'Trackers',
  class Trackers extends Neptune.PackageNamespace {}
);
