// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Commands/CommitLib/index.js

(module.exports = require('./namespace'))

.addModules({
  EditCommitMessage: require('./EditCommitMessage'),
  EditGitStage:      require('./EditGitStage'),
  SelectCoauthors:   require('./SelectCoauthors'),
  SelectCommitType:  require('./SelectCommitType'),
  StoryMenu:         require('./StoryMenu')
});