// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Commands/CommitLib/index.js

(module.exports = require('./namespace'))

.addModules({
  ActionMenu: require('./ActionMenu'),
  StoryMenu:  require('./StoryMenu')
});