// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Commands/CommitLib/index.js

(module.exports = require('./namespace'))

.addModules({
  ActionMenu:        require('./ActionMenu'),
  EditCommitMessage: require('./EditCommitMessage'),
  EditGitStage:      require('./EditGitStage'),
  SelectCommitType:  require('./SelectCommitType'),
  SelectPairs:       require('./SelectPairs'),
  StoryMenu:         require('./StoryMenu')
});