// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Commands/CommitLib/namespace.js

module.exports = require('../namespace').addNamespace(
  'CommitLib',
  class CommitLib extends Neptune.PackageNamespace {}
);
