// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Commands/CommandsLib/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./CommandsLib'))
.addModules({
  Auth:                require('./Auth'),
  CommitNow:           require('./CommitNow'),
  ConfigureMenu:       require('./ConfigureMenu'),
  EditCommitMessage:   require('./EditCommitMessage'),
  EditGitStage:        require('./EditGitStage'),
  EditStoryMenu:       require('./EditStoryMenu'),
  EditStoryName:       require('./EditStoryName'),
  FillInMissingState:  require('./fillInMissingState'),
  Lib:                 require('./Lib'),
  SelectCoauthors:     require('./SelectCoauthors'),
  SelectCommitFormat:  require('./SelectCommitFormat'),
  SelectCommitType:    require('./SelectCommitType'),
  SelectMembers:       require('./SelectMembers'),
  SelectStory:         require('./SelectStory'),
  SelectStoryEstimate: require('./SelectStoryEstimate'),
  SelectStoryState:    require('./SelectStoryState'),
  StoryMenu:           require('./StoryMenu')
});