// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Commands/CommandsLib/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./CommandsLib'))
.addModules({
  Auth:               require('./Auth'),
  CommandMenuLib:     require('./CommandMenuLib'),
  CommitNow:          require('./CommitNow'),
  EditCommitMessage:  require('./EditCommitMessage'),
  EditGitStage:       require('./EditGitStage'),
  FillInMissingState: require('./fillInMissingState'),
  Lib:                require('./Lib'),
  SelectCoauthors:    require('./SelectCoauthors'),
  SelectCommitType:   require('./SelectCommitType'),
  SelectStoryState:   require('./SelectStoryState'),
  StoryMenu:          require('./StoryMenu')
});