// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Commands/CommandsLib/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./CommandsLib'))
.addModules({
  Auth:               require('./Auth'),
  CommitNow:          require('./CommitNow'),
  ConfigureMenu:      require('./ConfigureMenu'),
  EditCommitMessage:  require('./EditCommitMessage'),
  EditGitStage:       require('./EditGitStage'),
  EditStoryMenu:      require('./EditStoryMenu'),
  FillInMissingState: require('./fillInMissingState'),
  Lib:                require('./Lib'),
  SelectCoauthors:    require('./SelectCoauthors'),
  SelectCommitType:   require('./SelectCommitType'),
  SelectMembers:      require('./SelectMembers'),
  SelectStory:        require('./SelectStory'),
  SelectStoryState:   require('./SelectStoryState'),
  StoryMenu:          require('./StoryMenu')
});