// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Commands/index.js

(module.exports = require('./namespace'))

.addModules({
  Add:            require('./Add'),
  Comment:        require('./Comment'),
  Commit:         require('./Commit'),
  Init:           require('./Init'),
  OpenTracker:    require('./OpenTracker'),
  ShowConfig:     require('./ShowConfig'),
  Stage:          require('./Stage'),
  StandardImport: require('./StandardImport'),
  Start:          require('./Start'),
  Status:         require('./Status'),
  Stories:        require('./Stories'),
  Version:        require('./Version'),
  Whoami:         require('./Whoami')
});
require('./CommitLib');