// generated by Neptune Namespaces v4.x.x
// file: GitGenUI/Commands/index.js

(module.exports = require('./namespace'))

.addModules({
  Commit:         require('./commit'),
  InitUserConfig: require('./InitUserConfig'),
  Start:          require('./Start'),
  WhoAmI:         require('./WhoAmI')
});