// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Lib/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Lib'))
.addModules({
  ApplyActions:     require('./applyActions'),
  Autocomplete:     require('./Autocomplete'),
  CommitStateLib:   require('./CommitStateLib'),
  IgnoreRejections: require('./ignoreRejections'),
  Presenters:       require('./Presenters'),
  SearchSort:       require('./SearchSort'),
  StandardImport:   require('./StandardImport')
});