// generated by Neptune Namespaces v4.x.x
// file: GitGenUI/Lib/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Lib'))
.addModules({
  Autocomplete:   require('./Autocomplete'),
  Git:            require('./Git'),
  SearchSort:     require('./SearchSort'),
  SourceRoots:    require('./SourceRoots'),
  StandardImport: require('./StandardImport')
});