// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/Widgets/index.js

(module.exports = require('./namespace'))

.addModules({
  InteractiveAdd: require('./InteractiveAdd'),
  StandardImport: require('./StandardImport')
});