// generated by Neptune Namespaces v4.x.x
// file: GitGenUi/PostCommitActions/index.js

(module.exports = require('./namespace'))

.addModules({
  AddStoryComment: require('./AddStoryComment'),
  AutoStartStory:  require('./AutoStartStory')
});